# Generated by Django 2.2.12 on 2020-06-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('location', models.CharField(max_length=35)),
                ('age', models.CharField(max_length=3)),
                ('contact', models.TextField()),
                ('profile', models.TextField()),
                ('experience', models.TextField()),
                ('qualifications', models.TextField()),
                ('hobbies', models.TextField()),
                ('references', models.TextField()),
            ],
        ),
    ]
